{{- if .Values.podDisruptionBudget.enabled }}
{{- $root := . -}}
{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "honeypot-foundry.fullname" $root }}-{{ $name }}
  labels:
    {{- include "honeypot-foundry.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  minAvailable: {{ $root.Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "honeypot-foundry.name" $root }}
      app.kubernetes.io/instance: {{ $root.Release.Name }}
      app.kubernetes.io/component: {{ $name }}
{{- end }}
{{- end }}
{{- end }}
